apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: bee-kn
spec:
  template:
    spec:
      containers:
        - image: quay.io/dbhagava/ui:v1
          env:
            - name: DESTINATION_URL
              value: http://destination-kn.test-namespace.svc.cluster.local